server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://k6b102.p.ssafy.io:3308/star?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: imlah
      password: imlah

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: k6b102.p.ssafy.io
    port: 6380
    password: imlah

  profiles:
    include: API-KEY, credentials